# Generated by Django 4.2.6 on 2023-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='mc_donalds.ProductOrder', to='mc_donalds.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='Состав не указан'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='labor_contract',
            field=models.IntegerField(),
        ),
    ]
